More progress on the CA creation bits

diff --git a/create-arkcase-ca b/create-arkcase-ca
--- a/create-arkcase-ca
+++ b/create-arkcase-ca
@@ -5,7 +5,6 @@ set -euo pipefail
 
 export BASE_DIR="$(dirname "${SCRIPT}")"
 export SCRIPT_DIR="${BASE_DIR}/.scripts"
-export CONF_DIR="${BASE_DIR}/conf"
 
 timestamp()
 {
@@ -32,6 +31,37 @@ err()
 	say "❌ ${@}"
 }
 
+validate_cert_secret()
+{
+	local CONTEXT="${1}"
+	local NAMESPACE="${2}"
+	local SECRET="${3}"
+	local KEY="${4}"
+
+	# Find the certificate secret
+	local JSON=""
+	JSON="$(kubectl --context "${CONTEXT}" --namespace "${NAMESPACE}" get secret "${SECRET}" -o json 2>/dev/null)" || return 1
+	[ -n "${JSON}" ] || return 1
+
+	# Decode the certificate from the secret
+	local CERT=""
+	CERT="$(jq --arg key "${KEY}" -r '.data[$key] // ""' 2>/dev/null <<< "${JSON}" | base64 -d 2>/dev/null)" || return 1
+
+	# Verify the certificate
+	openssl verify <(echo -n "${CERT}") &>/dev/null || return 1
+
+	# Verify that it's a CA certificate
+	openssl x509 -noout -in <(echo -n "${CERT}") -ext basicConstraints | tail -n +2 | grep -q -i -e '^[[:space:]]*CA:TRUE$' || return 1
+
+	# Ok ... it's valid, and is a CA ... use it!
+	return 0
+}
+
+cleanup()
+{
+	[ -v TEMPDIR ] && [ -n "${TEMPDIR}" ] && [ -d "${TEMPDIR}" ] && rm -rf "${TEMPDIR}" &>/dev/null
+}
+
 fail()
 {
 	err "${@}" 1>&2
@@ -43,58 +73,44 @@ NAMESPACE="arkcase-system"
 SECRET_NAME="arkcase-ca"
 
 # Check if the CA exists in the cluster
-EXISTS="false"
-kubectl --context "${CONTEXT}" --namespace "${NAMESPACE}" get secret "${SECRET_NAME}" &>/dev/null && EXISTS="true"
+EXISTS="true"
+validate_cert_secret "${CONTEXT}" "${NAMESPACE}" "${SECRET_NAME}" "crt" && quit "The ArkCase CA already exists and is still valid (from ${NAMESPACE}::${SECRET_NAME})"
 
-# If it exists, check validity
-if as_boolean "${EXISTS}" ; then
-	CERT="$(kubectl --context "${CONTEXT}" --namespace "${NAMESPACE}" get secret "${SECRET_NAME}" -o json | jq -r '.data.crt // ""' | base64 -d)"
-	if [ -n "${CERT}" ] ; then
-		# Check validity (it's a CA and isn't expired)
-		:
-	else
-		# No certificate in the secret, so it doesn't exist
-		EXISTS="false"
-	fi
-
-	# Delete the existing secret b/c it's invalid ...
-	kubectl --context "${CONTEXT}" --namespace "${NAMESPACE}" delete secret "${SECRET_NAME}"
-fi
-
-as_boolean "${EXISTS}" && quit "The ArkCase CA already exists and is still valid"
+# Delete the existing stuff, if any
+kubectl --context "${CONTEXT}" --namespace "${NAMESPACE}" delete secret "${SECRET_NAME}" &>/dev/null || true
 
 # Create the new CA!
-doing "Rendering a new CA certificate for ArkCase"
 TEMPDIR="$(mktemp -d)"
+trap cleanup EXIT
+
 CERT="${TEMPDIR}/ca.crt"
 KEY="${TEMPDIR}/ca.key"
-CONF="${TEMPDIR}/openssl.cnf"
-# TODO: Render config
-openssl req \
-	-days 3650 \
-	-nodes -new -x509 \
-	-keyout "${KEY}" \
-	-out "${CERT}" \
-	-config "${CONF}" \
-	"${@}" || fail "Failed to render a new CA certificate"
-ok "CA Certificate was rendered!"
 
-SECRET="
----
-apiVersion: v1
-kind: Secret
-metadata:
-  namespace: ${NAMESPACE}
-  name: ${SECRET_NAME}
-type: Opaque
-stringData:
-  crt: |-
-$(cat "${CERT}" | sed -e 's;^;    ;g')
-  key: |-
-$(cat "${KEY}" | sed -e 's;^;    ;g')
-"
+[ -v KEYBITS ] || KEYBITS=""
+[ -n "${KEYBITS}" ] || KEYBITS="2048"
+[[ "${KEYBITS}" =~ ^[1-9][0-9]*$ ]] || fail "The bit size [${KEYBITS}] is invalid"
+
+doing "Rendering a new CA certificate for ArkCase"
+openssl genrsa -out "${KEY}" ${KEYBITS} || fail "Failed to render a new private key for the CA"
+ok "A new ${KEYBITS} bit private key was rendered!"
+openssl req \
+	-new -x509 -nodes \
+	-days 3650 \
+	-key "${KEY}" \
+	-out "${CERT}" \
+	-subj "/CN=ArkCase Root CA/" || fail "Failed to render a new CA certificate"
+ok "The new CA Certificate was rendered!"
 
 say "Creating the secret ${NAMESPACE}::${SECRET_NAME} with the ArkCase CA"
-kubectl --context "${CONTEXT}" --namespace "${NAMESPACE}" create -f - <<< "${SECRET}"
+
+# If the namespace doesn't exist
+kubectl --context "${CONTEXT}" create namespace "${NAMESPACE}" &>/dev/null || true
+
+kubectl \
+	--context "${CONTEXT}" \
+	--namespace "${NAMESPACE}" \
+	create secret generic "${SECRET_NAME}" \
+	--from-file=crt="${CERT}" \
+	--from-file=key="${KEY}" \
 
 "${SCRIPT_DIR}/trust-cert" "${CERT}" "arkcase-root-ca"
